Description: Data Lake building. 

Resources: 

  DataLakeRawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault: 
            SSEAlgorithm: AES256
      BucketName: s3-aloha-production-data-lake-raw # Use sempre nomes padronizados!
      LoggingConfiguration: 
        LoggingConfiguration
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration: 
        Status: Enabled
      WebsiteConfiguration: 
        WebsiteConfiguration
      LifecycleConfiguration:
        Rules:
          - Id: abort-incomplete-multipart-uploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Id: move-old-objects-to-intelligent-tiering
            Status: Enabled
            Transitions:
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 90
          - Id: move-old-versions-to-cheaper-tiering
            Status: Enabled
            NoncurrentVersionTransitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 15

  DataLakeProcessedBucket:


  DataLakeCurated: