athena:
   target: athena
   outputs:
     athena:
       type: athena
       database: awsdatacatalog
       schema: data_lake_curated
       user: lucas
       pass: minha_senha_aws
       dbname: s3://s3-aloha-prod-athena-results
       threads: 4
       region_name: us-east-1